version: "3.8"

services:
  relay_server:
    build:
      context: ../
      dockerfile: test_env/Dockerfile.server
    ports:
      - "7464:7464"
    networks:
      - relay-network

  client:
    build:
      context: ../
      dockerfile: test_env/Dockerfile.client
    ports:
      - "8000-8999:8081"
      - "9000-9999:9081"
    networks:
      - relay-network


networks:
  relay-network:
    driver: bridge

