FROM tests_base:latest

ARG LATENCY=0ms
ARG RUST_LOG=info

ENV LATENCY=$LATENCY
ENV RUST_LOG=$RUST_LOG
ENV BIND_IP=0.0.0.0

# Example: BIND_IP_PATTERN=^172\.22\.
ENV BIND_IP_PATTERN=$BIND_IP_PATTERN
# Container IP
ENV BIND_IP=$BIND_IP

# Copy debug or release (prefered) build
COPY ./target/debu[g]/example[s]/http_clien[t] /app/
COPY ./target/releas[e]/example[s]/http_clien[t] /app/
RUN test -f /app/http_client || err "Failed to find http_client bin"

CMD export SERVER_IP=$(getent hosts relay_server | cut -d' ' -f1 | head -n 1); \
    echo "BIND_IP: '$BIND_IP', BIND_IP_PATTERN: '$BIND_IP_PATTERN', SERVER_IP: '$SERVER_IP'"; \
    if [ "$BIND_IP" != "0.0.0.0" ] &&  [ -n "$BIND_IP_PATTERN" ]; then \
        export BIND_IP=$(ip addr show | awk -v pattern="$BIND_IP_PATTERN" '/inet / && $2 ~ pattern {split($2, a, "/"); print a[1]}' | head -n 1); \
    fi; \
    if [ -n "$BIND_IP" ]; then \
        export P2P_BIND_ADDR=tcp://$BIND_IP:9081; \
        echo "Bind address: ${P2P_BIND_ADDR}"; \
    else echo "No bind address"; \
    fi; \
    tc qdisc add dev eth0 root netem delay $LATENCY \
    && /app/http_client \
    --api-port 8081 \
    --relay-addr tcp://$SERVER_IP:7464
