version: "3.8"

services:
  relay_server:
    build:
      context: ../
      dockerfile: test_env/Dockerfile.server
    cap_add:
    - NET_ADMIN
    ports:
      - "7464:7464/tcp"
      - "7464:7464/udp"
      - "7465:7465/tcp"
      - "7465:7465/udp"
    networks:
      - relay-network-1
      - relay-network-2

  client-1:
    environment:
      - RUST_LOG=debug
    build:
      context: ../
      dockerfile: test_env/Dockerfile.client
    cap_add:
    - NET_ADMIN
    ports:
      - "1998:8081"
      - "2998:9081"
    networks:
      - relay-network-1

  client-2:
    build:
      context: ../
      dockerfile: test_env/Dockerfile.client
    cap_add:
    - NET_ADMIN
    ports:
      - "1999:8081"
      - "2999:9081"
    networks:
      - relay-network-2

networks:
  relay-network-1:
    driver: bridge
  relay-network-2:
    driver: bridge

