FROM ubuntu:22.04

EXPOSE 8081

ENV RUST_LOG=info

RUN apt update && apt install -y iputils-ping dnsutils

COPY ./target/release /app
CMD export SERVER_IP=$(dig +short relay_server -t a); echo $SERVER_IP; \
    /app/examples/http_client \
        --api-port 8081 \
        --relay-addr tcp://$SERVER_IP:7464 \
        --p2p-bind-addr tcp://0.0.0.0:9081

