version: "3.8"

services:
  relay_server:
    build:
      context: ../
      dockerfile: test_env/Dockerfile.server
    cap_add:
    - NET_ADMIN
    networks:
      - client-network-1
      - client-network-2

  client-1:
    environment:
      - RUST_LOG=trace
    build:
      context: ../
      dockerfile: test_env/Dockerfile.client
    cap_add:
    - NET_ADMIN
    ports:
      - "1998:8081"
      - "2998:9081"
    networks:
      - client-network-1
    depends_on:
      - relay_server

  client-2:
    environment:
      - RUST_LOG=trace
    build:
      context: ../
      dockerfile: test_env/Dockerfile.client
    cap_add:
    - NET_ADMIN
    ports:
      - "1999:8081"
      - "2999:9081"
    networks:
      - client-network-2
    depends_on:
      - relay_server
      
networks:
  client-network-1:
    driver: bridge
  client-network-2:
    driver: bridge

