name: CI

on:
  pull_request

env:
  # `-D warnings` means any warnings emitted will cause build to fail
  RUSTFLAGS: "-D warnings -C opt-level=z -C debuginfo=1"
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: c:/vcpkg/installed/x64-windows

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Cmake
        run: |
          sudo apt-get install -y cmake
          cmake --version

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Cmake
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y cmake
          cmake --version

      - name: Unit tests
        run: cargo test --workspace
        env:
          RUST_BACKTRACE: 1

  integration_tests:
    name: Integration Tests
    needs:
      - checks
      - tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install tools
        uses: jdx/mise-action@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install --no-root
        working-directory: tests_integration

      - name: Initialize the test suite
        run: poetry run poe checks
        working-directory: tests_integration

      - name: Install system tools
        run: |
          sudo apt-get install -y cmake
          cmake --version

      - name: Build relay server
        run: cargo build -p ya-relay-server --release

      - name: Build http client
        run: cargo build -p ya-relay-client --example http_client --release

      - name: Run test suite
        run: poetry run pytest
        working-directory: tests_integration
